-- https://programmers.co.kr/learn/courses/30/lessons/59411
-- 오랜 기간 보호한 동물(2)

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO 
JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
ORDER BY DATEDIFF(AI.DATETIME, AO.DATETIME)
LIMIT 2;