-- https://programmers.co.kr/learn/courses/30/lessons/59412
-- 입양 시각 구하기(1)

SELECT HOUR(DATETIME) HOUR, COUNT(*)
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);


SELECT H.HOUR, H.COUNT
FROM
(
    SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) H
WHERE H.HOUR BETWEEN 9 AND 19
ORDER BY H.HOUR;