-- https://programmers.co.kr/learn/courses/30/lessons/59413
-- 입양 시각 구하기(2)

WITH RECURSIVE CTE(HOUR) AS
(
    SELECT 0
    UNION ALL
    SELECT HOUR + 1
    FROM CTE WHERE HOUR < 23
)
SELECT CTE.HOUR, 
        COALESCE(ANIMAL_CNT.COUNT, 0) COUNT 
FROM CTE
LEFT OUTER JOIN
(
    SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) ANIMAL_CNT
ON CTE.HOUR = ANIMAL_CNT.HOUR
ORDER BY HOUR;